apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secureshop-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: secureshop
  source:
    repoURL: https://github.com/Sirvickky001/argocd-main.git
    targetRevision: main
    path: secureshop-chart
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
